version: '3'
services:
  pulisher_node: # コンテナ名
    build:
      context: publisher_node
      dockerfile: Dockerfile  
    environment:
      NODE_NAME: "my_node"
      TOPIC_NAME: "amazon"
      PAYLOAD_SIZE: 128
      PERIOD_MS: 20
    container_name: publisher1

